"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("cuentas", [
      {
        titulo: "Ingresos por adelanto de tramites PRE JUB",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por adelanto de tramites JUB DEF",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por adelanto de tramites SENASIR",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por adelanto de tramites RETIRO FINAL",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por adelanto de tramites PENSION POR MUERTE",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por adelanto de tramites PENSION POR INVALIDEZ",
        ingreso: true,
        fk_subgrupo_cuenta: 1,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites PRE JUB",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites JUB DEF",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites SENASIR",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites RETIRO FINAL",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites PENSION POR MUERTE",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por culminación de tramites PENSION POR INVALIDEZ",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo:
          "Ingresos por comisión del 10% en beneficios logrados o ganados.",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por acompañamiento de trabajadora social.",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por consultas",
        ingreso: true,
        fk_subgrupo_cuenta: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por trasncripción de cartas",
        ingreso: true,
        fk_subgrupo_cuenta: 3,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por ventas de AVC - 07 -04 -05",
        ingreso: true,
        fk_subgrupo_cuenta: 3,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Ingresos por fotocopias",
        ingreso: true,
        fk_subgrupo_cuenta: 3,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Alquileres Percibidos",
        ingreso: true,
        fk_subgrupo_cuenta: 3,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Alquiler oficina",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Energía eléctrica",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Promoción y publicidad",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Telefonía celular",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Internet",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Material de escritorio",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Material de Aseo y Limpieza",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Servicio de Te y Refrigerio",
        ingreso: false,
        fk_subgrupo_cuenta: 4,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Administradora",
        ingreso: false,
        fk_subgrupo_cuenta: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 1",
        ingreso: false,
        fk_subgrupo_cuenta: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 2",
        ingreso: false,
        fk_subgrupo_cuenta: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 3",
        ingreso: false,
        fk_subgrupo_cuenta: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "SECRETARIA 4",
        ingreso: false,
        fk_subgrupo_cuenta: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "Administradora",
        ingreso: false,
        fk_subgrupo_cuenta: 6,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 1",
        ingreso: false,
        fk_subgrupo_cuenta: 6,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 2",
        ingreso: false,
        fk_subgrupo_cuenta: 6,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 3",
        ingreso: false,
        fk_subgrupo_cuenta: 6,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "SECRETARIA 4",
        ingreso: false,
        fk_subgrupo_cuenta: 6,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROFESIONAL EXTERNO 1",
        ingreso: false,
        fk_subgrupo_cuenta: 7,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROFESIONAL EXTERNO 2",
        ingreso: false,
        fk_subgrupo_cuenta: 7,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROMOTOR 1",
        ingreso: false,
        fk_subgrupo_cuenta: 8,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROMOTOR 2",
        ingreso: false,
        fk_subgrupo_cuenta: 8,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 1",
        ingreso: false,
        fk_subgrupo_cuenta: 9,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 2",
        ingreso: false,
        fk_subgrupo_cuenta: 9,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        titulo: "PROCURADOR 3",
        ingreso: false,
        fk_subgrupo_cuenta: 9,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("cuentas", null, {});
  },
};
