"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("menus", [
      {
        id: 1,
        name: "Dashboard",
        link: "/dashboard",
        icon: "mdiHome",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        name: "Consultorias",
        link: "",
        icon: "mdiFolderMultiple",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        name: "Agenda",
        link: "/consultas",
        icon: "mdiFolder",
        fk_menu: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        name: "Consultoria",
        link: "/mis-consultas",
        icon: "mdiAccountBoxMultipleOutline",
        fk_menu: 2,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        name: "Clientes",
        link: "",
        icon: "mdiAccountGroup",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        name: "Cliente",
        link: "/clientes",
        icon: "mdiAccountMultiple",
        fk_menu: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        name: "Contratos",
        link: "/contratos",
        icon: "mdiFile",
        fk_menu: 5,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        name: "Contabilidad",
        link: "",
        icon: "mdiCashMultiple",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        name: "Ingresos",
        link: "/ingresos",
        icon: "mdiCashPlus",
        fk_menu: 8,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        name: "Egresos",
        link: "/egresos",
        icon: "mdiCashMinus",
        fk_menu: 8,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 11,
        name: "Configuracion",
        link: "",
        icon: "mdiCogs",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 12,
        name: "Procesos y Requerimientos",
        link: "/procesos",
        icon: "mdiFileCog",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 13,
        name: "Servicios y Prestaciones",
        link: "/servicios_prestaciones",
        icon: "mdiFileCog",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 14,
        name: "Motivos",
        link: "/motivos",
        icon: "mdiFileCog",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 15,
        name: "Feriados",
        link: "/feriados",
        icon: "mdiCalendar",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 16,
        name: "Cuentas",
        link: "/cuentas",
        icon: "mdiBank",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 17,
        name: "Niveles",
        link: "/niveles",
        icon: "mdiKey",
        fk_menu: 11,
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 18,
        name: "Usuarios",
        link: "/procuradores",
        icon: "mdiAccountVoice",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 19,
        name: "Tareas",
        link: "/tareas",
        icon: "mdiClipboardCheckMultiple",
        created_by: 1,
        updated_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("menus", null, {});
  },
};
