"use strict";

const bcrypt = require('bcrypt');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("usuarios", [
      {
        fk_nivel: 1,
        usuario: "fvelasco",
        password: await bcrypt.hash("4986493", 10),
        nombres: "Freddy",
        apellidos: "Velasco",
        logins: 0,
        email: "fvelasco@gmail.com",
        ci: "1234657",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 1,
        usuario: "dcopa",
        password: await bcrypt.hash("7086114", 10),
        nombres: "Dan",
        apellidos: "Copa",
        logins: 0,
        email: "dcopa@gmail.com",
        ci: "1234657",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 1,
        usuario: "nblanco",
        password: await bcrypt.hash("6003423", 10),
        nombres: "Nilica",
        apellidos: "Blanco Aguirre",
        logins: 0,
        email: "nblanco@gmail.com",
        ci: "6003423 LP",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 1,
        usuario: "bblanco",
        password: await bcrypt.hash("4813861", 10),
        nombres: "Bertha",
        apellidos: "Blanco Aguirre",
        logins: 0,
        email: "bblanco@gmail.com",
        ci: "4813861 LP",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 1,
        usuario: "ablanco",
        password: await bcrypt.hash("7029153", 10),
        nombres: "Abel Efrain",
        apellidos: "Blanco Aguirre",
        logins: 0,
        email: "ablanco@gmail.com",
        ci: "7029153 LP",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 1,
        usuario: "hblanco",
        password: await bcrypt.hash("12345554", 10),
        nombres: "Habram",
        apellidos: "Blanco Aguirre",
        logins: 0,
        email: "hblanco@gmail.com",
        ci: "12345554 LP",
        celular: "1234657",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 2,
        usuario: "rticona",
        password: await bcrypt.hash("9123100", 10),
        nombres: "Rubi Esmeralda",
        apellidos: "Ticona Quisbert",
        logins: 0,
        email: "rubi.ticona26@gmail.com",
        ci: "9123100 LP",
        celular: "73264120",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 2,
        usuario: "ilujan",
        password: await bcrypt.hash("11542181", 10),
        nombres: "Isabel Rebeca",
        apellidos: "Lujan Mamani",
        logins: 0,
        email: "isitalujan123@gmail.com",
        ci: "11542181 LP",
        celular: "69844070",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 2,
        usuario: "crodriguez",
        password: await bcrypt.hash("9144127", 10),
        nombres: "Carla Eliana",
        apellidos: "Rodriguez Aguirre",
        logins: 0,
        email: "rodriguezaguirrecarlaeliana@gmail.com",
        ci: "9144127 LP ",
        celular: "71256034",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        fk_nivel: 2,
        usuario: "mchoque",
        password: await bcrypt.hash("4949343", 10),
        nombres: "Marcial",
        apellidos: "Choque Jillapa",
        logins: 0,
        email: "marcial@gmail.com",
        ci: "4949343 PT",
        celular: "60128357",
        is_active: true,
        created_at: new Date(),
        updated_at: new Date(),
      }
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("usuarios", null, {});

  },
};
